- moved userinfo_url
Rukenshia/ueberauth_keycloak pull request #2
Opened 2019-02-16 20:07 UTC by rflaperuta

My first serious PR, your feedback is very important...

- Updated version number to 0.2.0
- Moved userinfo_url inside `Ueberauth.Strategy.Keycloak.OAuth` exposed it though a function
- Did some tinkering with configuration loading

Thx

2019-02-21 11:23 UTC, Rukenshia requested changes
Thanks a lot for submitting this, it's much appreciated. Just left two small comments. I forgot about the PR, sorry for that!

2019-02-21 11:23 UTC, Rukenshia commented on lib/ueberauth/strategy/keycloak/oauth.ex
> +  def userinfo_url() do
Can you add a short docstring here on what the function does?

2019-02-21 11:23 UTC, Rukenshia commented on lib/ueberauth/strategy/keycloak/oauth.ex
> +  defp config() do
Can you add a short docstring on what this function does (e.g. it would be useful to say where it is grabbing the config from)

2019-02-28 04:03 UTC, rflaperuta commented
Hello @Rukenshia! Added another commit about the docstrings, please tell me if it is good...

Thx

2019-02-28 08:50 UTC, Rukenshia approved these changes

2019-02-28 08:50 UTC, merged